---
index:
  max_result_window: 10000
  max_inner_result_window: 5000
  number_of_shards: 1
  number_of_replicas: 1
  max_ngram_diff: 7
  analysis:
    normalizer:
      lowercase:
        type: custom
        filter:
          - lowercase
